Kafka indexer
haim1993/boot-bootcamp pull request #4
Opened 2019-12-15 09:03 UTC by haim1993

2019-12-17 13:12 UTC, naorgu requested changes
Great work 👏

2019-12-17 13:12 UTC, naorgu commented on infrastructure/src/main/java/juice/modules/ElasticSearchModule.java
> +public class ElasticSearchModule extends AbstractModule {
This seems more like `ElasticsearchClientModule`

2019-12-17 13:12 UTC, naorgu commented on indexer/src/main/java/juice/modules/KafkaConsumerModule.java
> +    private final String fileUrl;
Let's rename all `fileUrl` occurrences to ...FilePath, i.e.

```suggestion
    private final String kafkaConsumerFilePath;
```

2019-12-17 13:12 UTC, naorgu commented on indexer/src/main/java/consumer/IndexConsumer.java
> +                    System.out.printf("Consumer Record:(%d, %s, %d, %d)\n", record.key(), record.value(),
Let's use `Logger.debug` as we don't want to print log per consumed message (imagine 10 million messages consumed...)

2019-12-17 13:12 UTC, naorgu commented on indexer/src/main/java/consumer/IndexConsumer.java
> +    public void run() {
Should be private

2019-12-17 13:12 UTC, naorgu commented on indexer/src/main/java/consumer/IndexConsumer.java
> +            }
So looks like you currently use kafka's auto-commit. As we mentioned, auto-commit behaviour can result with message lost (i.e. message consumed, indexing failed, and after auto-commit interval, offset was committed. then message will never be indexed).
Instead, let's switch to a manual commit

2019-12-17 13:12 UTC, naorgu commented on indexer/src/main/java/jersey/rest/GracefulShutdownResource.java
> +public class GracefulShutdownResource {
💯

2019-12-17 13:12 UTC, naorgu commented on indexer/src/main/java/consumer/IndexConsumer.java
> +                    System.out.println("Bulk: There's a problem master...");
Let's get use to `Logger` instead of system out prints. In this case should be `Logger.error`

2019-12-17 13:12 UTC, naorgu commented on infrastructure/src/main/java/config/ConfigurationFactory.java
> +public class ConfigurationFactory {
Very nice abstraction ✨

2019-12-17 13:12 UTC, naorgu commented on logs-shipper/src/test/java/ResourceTest.java
> +        String randomString = generateString(new Random(), SOURCES, 100);
`generateString` can be private

2019-12-17 13:12 UTC, naorgu commented on logs-shipper/src/test/java/ResourceTest.java
>  public class ResourceTest {
Let's rename to `IndexAndQueryE2ETest`

2019-12-17 13:12 UTC, naorgu commented on logs-shipper/src/main/java/RestHandler.java
> +public class RestHandler {
This sounds more like `LogsShipperClient`

2019-12-17 13:12 UTC, naorgu commented on logs-shipper/src/test/java/ResourceTest.java
>          assertNotNull(indexResponse);
Afterwards, you do `Thread.sleep(1000)` between indexing and querying. This can be problematic, as 1 sec could be too short, then the test will fail.
Instead, let's use "wait until` behaviour. Ask Guy Kremer for reference

2019-12-17 13:12 UTC, naorgu commented on logs-shipper/src/main/java/RestHandler.java
> -package com;
Let's put inside `client` package

2019-12-17 13:12 UTC, naorgu commented on indexer/src/main/java/LogEngine.java
> +public class LogEngine {
Let's match the Main class name to the name of the module

2019-12-17 13:12 UTC, naorgu commented on logs-shipper/src/main/java/Listener.java
> +public class Listener {
Let's match the main class to the name of the module

2019-12-17 13:12 UTC, naorgu commented on logs-shipper/src/main/java/jersey/rest/IndexResource.java
> +class RequestIndexMessage {
This probably needs to be `static class`, and be inside the `IndexResource` scope

2019-12-17 13:12 UTC, naorgu commented on logs-shipper/src/main/java/jersey/rest/IndexResource.java
> +            return Response.status(HttpURLConnection.HTTP_BAD_REQUEST).entity("Producer failed to communicate with kafka\n").build();
The client that calls `index` request doesn't know who is Kafka - it's an internal detail. Let's change to a user-friendly error message

2019-12-17 13:12 UTC, naorgu commented on logs-shipper/src/main/java/jersey/rest/IndexResource.java
> +            producer.send(new ProducerRecord<>(TOPIC, PRODUCER_MESSAGE_COUNT++, msg)).get();
Might be more simple to use the `String topic, V value` constructor

2019-12-17 13:12 UTC, naorgu commented on logs-shipper/src/main/java/jersey/rest/IndexResource.java
> +            producer.flush();
Why you need the `.get()` and `.flush()` ?

2019-12-17 13:12 UTC, naorgu commented on logs-shipper/src/main/java/jersey/rest/IndexResource.java
> +    public void setMessage(String message) { this.message = message; }
setters are redundant

2019-12-17 13:12 UTC, naorgu commented on logs-shipper/src/main/java/jersey/rest/IndexResource.java
> +    public Map<String, Object> buildDocToIndex(RequestIndexMessage requestIndexMessage, String userAgent) {
private

2019-12-17 13:12 UTC, naorgu commented on logs-shipper/src/main/java/jersey/rest/IndexResource.java
> +    public Map<String, Object> buildDocToIndex(RequestIndexMessage requestIndexMessage, String userAgent) {
The name `buildDocToIndex` should change, as the message now going to kafka

2019-12-17 13:12 UTC, naorgu commented on logs-shipper/src/main/java/jersey/rest/IndexResource.java
> +            ObjectMapper mapper = new ObjectMapper();
You can create single `ObjectMapper` on constructor, then use the same one in each request

2019-12-17 13:12 UTC, naorgu commented on logs-shipper/src/main/java/jersey/rest/SearchResource.java
> +    public SearchSourceBuilder getMatchQuerySourceBuilder(Tuple<String,String>... args) {
private

2019-12-17 13:12 UTC, naorgu commented on indexer/src/main/java/config/ConsumerConfiguration.java
> +    private String id;
Let's rename to `groupId`

2019-12-17 13:12 UTC, naorgu commented on logs-shipper/src/main/java/config/ProducerConfiguration.java
> +    private String id;
```suggestion
    private String clientId;
```

2019-12-19 14:44 UTC, haim1993 commented on logs-shipper/src/main/java/jersey/rest/IndexResource.java
> +class RequestIndexMessage {
sounds good!

2019-12-19 14:44 UTC, haim1993 commented on logs-shipper/src/main/java/jersey/rest/IndexResource.java
> +            producer.flush();
I thought i needed it. I read about it now, and i don't.

2019-12-19 14:44 UTC, haim1993 commented on logs-shipper/src/main/java/jersey/rest/IndexResource.java
> +    public void setMessage(String message) { this.message = message; }
not really...

the method index(...) takes as parameter an object of RequestIndexMessage. It needs to create an instance of it.
Using a constructor to create it won't work. Only with setter!

2019-12-22 14:28 UTC, naorgu approved these changes
👌

2019-12-23 10:36 UTC, merged